# Generated by Django 3.2.4 on 2021-06-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='the hotel building name')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=50, verbose_name='the type of fuel')),
                ('unit', models.CharField(max_length=50, verbose_name='the unit of the fuel type')),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.building')),
            ],
        ),
        migrations.CreateModel(
            name='Halfhourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='the fuel consumption within the past half hour')),
                ('reading_date_time', models.DateTimeField(verbose_name='the end time of the half hour duration')),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.meter')),
            ],
        ),
    ]
